spring.application.name=discografia
spring.data.mongodb.uri=mongodb+srv://macajuliodediaz_db_user:julio1997@eva-u2-spring.kqylaal.mongodb.net/?retryWrites=true&w=majority
spring.data.mongodb.database=discografica-db